version: '3'

services:
  aurox-webhook:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.webhook
    container_name: webhook
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db/postgres"
      WEBHOOK_PASSWORD: "${WEBHOOK_PASSWORD}"
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - backend
    volumes:
      - ./app:/app
  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend
    volumes:
      - "db-data:/var/lib/postgresql/data"

networks:
  proxy:
    external: true
  backend:
    external: false

volumes:
  db-data:

