version: '3.7'

services:
  webhook:
    build:
      context: .
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '0.0.0.0:80' ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      DATABASE_URL: 'postgresql://postgres:${POSTGRES_PASSWORD}@db/aurox'
      WEBHOOK_PASSWORD: '${WEBHOOK_PASSWORD}'
      LOG_LEVEL: 'DEBUG'
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true
    networks:
      - 'srv'
      - 'backend'
    ports:
      - '80:80'
    volumes:
      - './app:/app'
      - './log:/log'

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: 'aurox'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - 'backend'
    ports:
      - '127.0.0.1:2345:5433'

volumes:
  postgres:

networks:
    srv:
      external: true
    backend:
      external: false
