version: "3"

services:
  reverse-proxy:
    image: traefik:v2.8.3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      # Web
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the static configuration into the container
      - ./config/static.yaml:/etc/traefik/traefik.yaml:ro
      # Map the dynamic configuration into the container
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      # Map the certificates into the container
      - ./certs:/etc/certs:ro
    networks:
      - proxy
    environment:
      - TRAEFIK_BASIC_AUTH

networks:
  proxy:
    external: true
