# to integrated with https://github.com/tomMoulard/make-my-server

version: '3'

services:
  webhook:
    image: 5queezer/webhook:latest
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '0.0.0.0:80' ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db/postgres"
      WEBHOOK_PASSWORD: "${WEBHOOK_PASSWORD}"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.webhook.rule=Host(`${SITE:-localhost}`) && PathPrefix(`/webhook`)}`)'
      - 'traefik.http.services.webhook.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.strip.stripprefix.prefixes=/webhook'
      - 'traefik.http.routers.webhook.middlewares=strip'
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true
    networks:
      - 'srv'

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "./webhook/data:/var/lib/postgresql/data"
    labels:
      - 'traefik.enable=false'

networks:
    srv:
      external: true
