version: "3.9"

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db/postgres"
      WEBHOOK_PASSWORD:
    depends_on:
      - db
    networks:
      - back-tier
      - front-tier
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - back-tier
    volumes:
      - "db-data:/var/lib/postgresql/data"

networks:
  front-tier: {}
  back-tier: {}

volumes:
  db-data:

