http:
  routers:
    traefik:
      rule: "Host(`traefik.`{{env "PRIMARY_DOMAIN"}}`)"
      service: "api@internal"
      middlewares:
        - authtraefik

      tls:
        certResolver: le
        domains:
          - main: '`{{env "PRIMARY_DOMAIN"}}`'
            sans:
              - '`*.{{env "PRIMARY_DOMAIN"}}`'
#    webhook:
#      rule: "Host(`webhook.docker.localhost`)"
#      tls:
#        certResolver: le
#        domains:
#          - main: "docker.localhost"
#            sans:
#              - "*.docker.localhost"

  middlewares:
    authtraefik:
      basicAuth:
        users:
          # To create a user:password pair, the following command can be used:
          # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
          - `{{env "TRAEFIK_BASIC_AUTH"}}`
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
