global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: ${TRAEFIK_SSLEMAIL?Variable not set}
      storage: ./acme.json
      tlsChallenge: true
